apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: ClusterIP  # Change the type to ClusterIP
  clusterIP: 10.96.0.5  # Specify the desired IP address
  selector:
    app: service1
  ports:
    - protocol: TCP
      port: 8093
      targetPort: 8093
---
apiVersion: v1
kind: Pod
metadata:
  name: service1
  annotations:
    "cni.projectcalico.org/ipAddrs": '["192.168.0.129"]'
spec:
  containers:
  - name: service1
    image: ceyi/s_eins:latest
    imagePullPolicy: IfNotPresent
    ports:
     - containerPort: 8090
---
apiVersion: v1
kind: Pod
metadata:
  name: service2
  annotations:
    "cni.projectcalico.org/ipAddrs": '["192.168.0.130"]'
spec:
  containers:
  - name: service2
    image: ceyi/s_eins:latest
    imagePullPolicy: IfNotPresent
    ports:
     - containerPort: 8091
---
apiVersion: v1
kind: Pod
metadata:
  name: service3
  annotations:
    "cni.projectcalico.org/ipAddrs": '["192.168.0.131"]'
spec:
  containers:
  - name: service3
    image: ceyi/s_eins:latest
    imagePullPolicy: IfNotPresent
    ports:
     - containerPort: 8092
